version: '3'

services:
  postgres-server:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - flashcards-network
    volumes:
      - ./database:/var/lib/postgresql
      
  pgAdmin-server:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    depends_on:
      - postgres-server
    networks:
      - flashcards-network

  backend-server:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: flashcards/flashcards-backend
    ports: 
      - "8081:8081"
    networks:
      - flashcards-network
    environment: 
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8081  

networks: 
  flashcards-network:
    driver: bridge
