CREATE SCHEMA IF NOT EXISTS FLASHCARDS;

drop table flashcards.answer if exists;
drop table flashcards.deck if exists;
drop table flashcards.deck_test_result if exists;
drop table flashcards.difficulty if exists;
drop table flashcards.flashcard if exists;
drop table flashcards.profile if exists;
drop table flashcards.tb_user if exists;
drop sequence if exists flashcards.sq_answer;
drop sequence if exists flashcards.sq_deck;
drop sequence if exists flashcards.sq_deck_test_result;
drop sequence if exists flashcards.sq_flashcard;
drop sequence if exists flashcards.sq_user;
drop table tb_user_profiles if exists;
drop sequence if exists profile_sq;
create sequence flashcards.sq_answer start with 1 increment by 1;
create sequence flashcards.sq_deck start with 1 increment by 1;
create sequence flashcards.sq_deck_test_result start with 1 increment by 1;
create sequence flashcards.sq_flashcard start with 1 increment by 1;
create sequence flashcards.sq_user start with 1 increment by 1;
create table flashcards.answer (id bigint not null, difficulty_id bigint, question_id bigint, test_result_id bigint, primary key (id));
create table flashcards.deck (id bigint not null, active boolean, description varchar(200) not null, name varchar(100) not null, timestamp timestamp not null, cod_user bigint not null, primary key (id));
create table flashcards.deck_test_result (id bigint not null, timestamp timestamp, deck_id bigint, user_id bigint, primary key (id));
create table flashcards.difficulty (id bigint not null, description varchar(100), primary key (id));
create table flashcards.flashcard (id bigint not null, active boolean, answer varchar(4000) not null, question varchar(100) not null, time_stamp timestamp not null, cod_deck bigint not null, primary key (id));
create table flashcards.profile (id bigint not null, profile varchar(255), primary key (id));
create table flashcards.tb_user (id bigint not null, email varchar(100) not null, first_name varchar(100) not null, last_name varchar(100) not null, password varchar(100) not null, timestamp timestamp not null, username varchar(100) not null, primary key (id));
alter table flashcards.difficulty add constraint UK_7ve8pxg0ji6tmfv269b7grykg unique (description);
create sequence profile_sq start with 1 increment by 50;
create table tb_user_profiles (user_id bigint not null, profiles_id bigint not null);
alter table flashcards.answer add constraint FKp5b6b6oorfs9fefycy73puk2s foreign key (difficulty_id) references flashcards.difficulty;
alter table flashcards.answer add constraint FKdwu3psh4o48xng6pksvw1kx9p foreign key (question_id) references flashcards.flashcard;
alter table flashcards.answer add constraint FKcfwhkghh5bvsk65mn0jjxf4md foreign key (test_result_id) references flashcards.deck_test_result;
alter table flashcards.deck add constraint FKon6i0dcwvueo43fipvehj6aji foreign key (cod_user) references flashcards.tb_user;
alter table flashcards.deck_test_result add constraint FKkbn01qkrcxoq32blq007e5j22 foreign key (deck_id) references flashcards.deck;
alter table flashcards.deck_test_result add constraint FKkg4nivky7v132be81bgf9chd5 foreign key (user_id) references flashcards.tb_user;
alter table flashcards.flashcard add constraint FK1ylpb767a3rqlfadhu36g4y3g foreign key (cod_deck) references flashcards.deck;
alter table tb_user_profiles add constraint FK39xsoumctlbcn26qokmgwu7q9 foreign key (profiles_id) references flashcards.profile;
alter table tb_user_profiles add constraint FK5wdmk99qusbns85aa7a4nv8yt foreign key (user_id) references flashcards.tb_user;
